# Generated by Django 3.2.9 on 2021-12-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pricing_table',
        ),
    ]
