# Generated by Django 3.2.10 on 2022-01-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_category_pricing_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-Name'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
