# Generated by Django 3.2.10 on 2022-01-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_auto_20220104_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',)},
        ),
    ]
