# Generated by Django 3.2.10 on 2022-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
